### ISSUE TITLE
3.9.0 BETA Support

### ISSUE THREAD

**Issue by dbpprt** [Caribou3d/CaribouMK3s-Firmware#26]
Prusa recently released 3.9.0 BETA. It would be great to have releases available for the BETA version to get the benefits of LA1.5.

Best, Dennis

**Comment by 3d-gussner** [comment]
@dennisbappert Hi Denis thanks for opening this issue. As it is a Beta where things can go wrong we decided not to make it public and send few people the Beta Firmware. I think that FW 3.9.0-RC1 will come soon and we will publish this as soon as possible.

**Comment by dbpprt** [comment]
Still no updates?

**Comment by 3d-gussner** [comment]
Sorry, we forgot to update this issue. There is a new branch for FW3.9.0, which been tested by few Zaribo Facebook members.

**Comment by 3d-gussner** [comment]
@dennisbappert Please checkout https://github.com/Zaribo/Zaribo-Firmware/tree/Zaribo-MK3-FW3.9.0
Also hitting the github watch could help you to see if something new has been posted.

**Comment by dbpprt** [comment]
Thank you very much, are there precompiled binaries available for 3.9.0, too?

**Comment by 3d-gussner** [comment]
The final will be there very soon and we will provide these. Please stay tuned.

**Comment by 3d-gussner** [comment]
@dennisbappert final is there. I will close this issue.
