### ISSUE TITLE
[BUG]Display shows random characters after a while

### ISSUE THREAD

**Issue by SimonTil** [Caribou3d/CaribouMK3s-Firmware#29]
Branch: Zaribo-MK2
Printer: Original Prusa MK2S (with RAMBo 1.3)
Display: Upgraded to Zaribo OLED (https://zaribo.com/home/245-oled-display-20x4-white-black-by-ldo.html)

**Describe the bug**
After compiling the original source code as downloaded here (https://github.com/Zaribo/Zaribo-Firmware/tree/Zaribo-MK2) and placing the Configuration_prusa.h file in the Firmware folerd, the display booted fine, but after a few seconds, random characters appear, and I can't figure out why.
Tried it as well with the MK2 (without Zaribo) branch, but then the display didn't show anything.
**Video**
Video (zipped): [Bug_Display.zip](https://github.com/Zaribo/Zaribo-Firmware/files/4941826/Bug_Display.zip)

**Comment by 3d-gussner** [comment]
Sorry for the late response, I must have missed the email. Get tons of github mails, need to make a rule in mail to sort them.

Issue is that MK2 firmware has been touched last year or so. The MK3 branch supports only MK3, MK3s, MK2.5 and MK2.5s

I will try to have a look if we can get OLED for the MK2, but as it is very rare I didn't spend time on that.
