### ISSUE TITLE
[BUG] XYZ- calibration fails with FW3.10.0 MK3S 220

### ISSUE THREAD

**Issue by Leuprochon** [Caribou3d/CaribouMK3s-Firmware#35]
**Printer type** - [e.g. MK3S, MK3, MK2.5S, MK2.5, MK2S, MK2]

MK3S 220 Rel 3

10mm rods
Bondtech
e3d hotend
320 Meanwell
40w heater
BuildTak steel sheet

**Printer firmware version**-  [e.g. 3.8.1, 3.8.1-RC1, ...]

FW3.10.0

**Describe the bug**

When I start the XYZ calibration the pinda doesn't find the bed point. It's impossible to calibrate my printer with XYZ calibration menu. Mainly it's happen on the first point but sometime on another point. So I reinstal the older firmware (3.9.3) with wich I don't had this issue.

**Comment by 3d-gussner** [comment]
@Leuprochon Which MK3S 220 do you have?
8mm rods
Bondtech
etc...

**Comment by Leuprochon** [comment]
@3d-gussner 

Sorry for forget it

So here :

10mm rods
Bondtech
e3d hotend
320 Meanwell
40w heater
BuildTak steel sheet

**Comment by wschadow** [comment]
It's a bug in the initial release of 3.10.0. Please try the new release.
